/**
 * Numbers used on the homepage to show how the energy landscape is moving,
 * in Arizona and nationally.
 *
 * RULES FOR THIS FILE — read before editing:
 *
 * 1. SOURCE QUALITY COMES FIRST. Prefer primary sources: EIA, Berkeley Lab,
 *    DOE, the Arizona Corporation Commission, a utility's own IRP filing.
 *    Trade associations and advocacy groups (SEIA, CEA, EEI, AWEA, API) publish
 *    real numbers, but they select and frame them to argue a position. If a
 *    figure exists only in an advocacy publication, leave it out. The whole
 *    value of this section is that a reader can check us and find we were
 *    straight with them; one motivated statistic costs more than it earns.
 * 2. Every entry carries a checkable source and the date the figure was
 *    published. No number goes on the site without one.
 * 3. `asOf` is when the figure was published or last confirmed, not when this
 *    file was edited. It renders on the page so a reader can judge staleness.
 * 4. Re-check these at the start of each semester. A wrong number on a public
 *    site is worse than no number.
 */

export type Stat = {
  /** The figure itself. Kept short — it is set in display type. */
  value: string;
  /** Unit or qualifier shown next to the value. Optional. */
  unit?: string;
  /** One or two plain sentences saying what the number means. */
  body: string;
  /** Who published it. */
  source: string;
  sourceUrl: string;
  /** Publication date of the figure, e.g. "August 2025". */
  asOf: string;
};

/** EIA's Arizona State Energy Profile, the primary source for most of below. */
const EIA_AZ = "https://www.eia.gov/state/analysis.php?sid=AZ";

export const arizonaStats: Stat[] = [
  {
    value: "38% → 8%",
    body: "Coal's share of Arizona's electricity generation, 2014 to 2024. The Navajo Generating Station, once the state's second-largest power plant, closed in 2019, and the last coal mine in Arizona shut the same year. An entire fuel left the state's mix inside a decade.",
    source: "EIA, Arizona State Energy Profile",
    sourceUrl: EIA_AZ,
    asOf: "July 2025 (2024 data)",
  },
  {
    value: "3,900 → 7,700",
    unit: "MW",
    body: "Battery storage in Arizona: roughly 3,900 MW operating, with another 3,807 MW planned to come online by 2026. The state's storage fleet is set to about double in two years.",
    source: "EIA, Arizona State Energy Profile",
    sourceUrl: EIA_AZ,
    asOf: "July 2025 (May 2025 inventory)",
  },
  {
    value: "30,000",
    unit: "MW",
    body: "Data center interconnection requests sitting in Arizona Public Service's queue, against a system that peaks around 8,200 MW. Most of that will never get built — but deciding which part does is the job.",
    source: "APS, quoted in Distilled",
    sourceUrl: "https://www.distilled.earth/p/data-centers-are-pushing-arizonas",
    asOf: "2026",
  },
  {
    value: "27",
    unit: "%",
    body: "Share of Arizona's electricity generated by Palo Verde alone — the largest power plant in the state and the second-largest nuclear plant in the country. It supplies about 4% of all US nuclear generation.",
    source: "EIA, Arizona State Energy Profile",
    sourceUrl: EIA_AZ,
    asOf: "July 2025 (2024 data)",
  },
  {
    value: "4th",
    body: "Arizona's national rank in solar generation, behind California, Texas and Florida, off nearly 9,000 MW of capacity. Solar passed hydroelectric here for the first time in 2017 and reached 13% of total generation in 2024.",
    source: "EIA, Arizona State Energy Profile",
    sourceUrl: EIA_AZ,
    asOf: "July 2025 (2024 data)",
  },
  {
    value: "3 of 3",
    body: "APS, SRP and Tucson Electric Power all broke their all-time peak demand records in the same week in August 2025. Every major utility in the state, at once.",
    source: "Utility Dive",
    sourceUrl:
      "https://www.utilitydive.com/news/arizona-aps-tep-srp-peak-demand-record/757395/",
    asOf: "August 2025",
  },
];

export const nationalStats: Stat[] = [
  {
    value: "4.4% → 12%",
    body: "Data centers used 4.4% of all US electricity in 2023. Berkeley Lab puts them at 6.7–12% by 2028 — 176 TWh growing to somewhere between 325 and 580 TWh in five years.",
    source: "Berkeley Lab / DOE",
    sourceUrl:
      "https://newscenter.lbl.gov/2025/01/15/berkeley-lab-report-evaluates-increase-in-electricity-demand-from-data-centers/",
    asOf: "December 2024",
  },
  {
    value: "4 years",
    body: "US electricity demand has now risen four years running — the first time since 2007, and the strongest four-year stretch since 2000. The flat-demand era that most of the grid was planned around is over.",
    source: "EIA",
    sourceUrl: "https://www.eia.gov/pressroom/releases/press582.php",
    asOf: "January 2026",
  },
  {
    value: "70",
    unit: "GW",
    body: "New solar capacity behind EIA's forecast that US solar generation grows 21% in both 2026 and 2027 — the largest increase of any source.",
    source: "EIA",
    sourceUrl: "https://www.eia.gov/pressroom/releases/press582.php",
    asOf: "January 2026",
  },
];
